name: Scheduled Cron Job

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight UTC

  workflow_dispatch: # Allows manual execution from GitHub Actions UI

jobs:
  cron-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run a script
        run: |
          echo "Running cron job..."
          curl -X GET "${{ secrets.API_URL }}"
