name: Update Event Status Cron Job

on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes (Modify as needed)
  workflow_dispatch:  # Allows manual execution

jobs:
  update-events:
    runs-on: ubuntu-latest

    steps:
      - name: Run API to Update Events
        run: |
          curl -X GET "${{ secrets.API_URL }}"
